name: 'Install WASI SDK'
description: 'Install a WASI SDK toolchain for WebAssembly development'

inputs:
  version:
    description: 'WASI SDK version to install (e.g., "25", "24", "23")'
    required: false
    default: 'latest'
  install-path:
    description: 'Directory to install WASI SDK to'
    required: false
    default: ${{ runner.tool_cache }}/wasi-sdk
  add-to-path:
    description: 'Add WASI SDK bin directory to PATH'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token for API requests (avoids rate limiting)'
    required: false
    default: ${{ github.token }}

outputs:
  wasi-sdk-path:
    description: 'Path to the installed WASI SDK'
    value: ${{ steps.install.outputs.wasi-sdk-path }}
  wasi-sdk-version:
    description: 'Version of WASI SDK that was installed'
    value: ${{ steps.install.outputs.wasi-sdk-version }}
  clang-path:
    description: 'Path to the clang executable'
    value: ${{ steps.install.outputs.clang-path }}
  sysroot-path:
    description: 'Path to the WASI sysroot'
    value: ${{ steps.install.outputs.sysroot-path }}

runs:
  using: 'composite'
  steps:
    - name: Install WASI SDK
      id: install
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        $GITHUB_ACTION_PATH/install.py -v \
          --version '${{ inputs.version }}' \
          --install-dir '${{ inputs.install-path }}' \
          ${{ inputs.add-to-path == 'true' && '--add-to-path' || '' }}
